### ISSUE TITLE
AW Error on addon loading

### ISSUE THREAD

**Issue by AveUrsus** [notour/AirWarlock#10]
Callback UpdateWarlockDataCAllback doesnot exist in this addon
such message thrown for 5 calls

**Comment by notour** [comment]
which version do you use ? the alpha or the release ?

**Comment by AveUrsus** [comment]
Release v1.1

**Comment by notour** [comment]
ok i found another bug, i have a raid to nigh and i will try to fixe after

**Comment by AveUrsus** [comment]
by the way - there is a little bug with interface window - when you move addon window - warlok bars are staing at there places

**Comment by notour** [comment]
look at the branch (https://github.com/notour/AirWarlock/tree/bug/10-display-issue-v1.1) if it fixed your issue. 
I couldn't reproduce you bug but i detect others. So may be the one you had was a side effect

**Comment by AveUrsus** [comment]
> look at the branch (https://github.com/notour/AirWarlock/tree/bug/10-display-issue-v1.1) if it fixed your issue.
> I couldn't reproduce you bug but i detect others. So may be the one you had was a side effect

This branch is showing window correctly.

**Comment by notour** [comment]
Thanks for your report don't hesitate to raised issue if it append in the future (il will publish the fixe in the version 1.1.1

**Comment by notour** [comment]
V1.1.1
